// Testes de comportamento DOM; não substituem inspeção visual em navegador.
const {JSDOM}=require('jsdom');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const settle=()=>new Promise(r=>setTimeout(r,15));
function setup(html,script,fetch){const d=new JSDOM(html,{url:'https://example.test/kaka/conta',runScripts:'outside-only',pretendToBeVisual:true});d.window.fetch=fetch;const intervals=[];d.window.setInterval=f=>intervals.push(f);d.window.eval(fs.readFileSync(path.join(__dirname,'../static',script),'utf8'));return {w:d.window,intervals};}
(async()=>{
let messages=[],postResolve;const {w,intervals}=setup('<div data-chat-url="/messages" data-last-id="0"><i data-chat-empty></i></div><form data-chat-form><textarea name="message" required></textarea><button>Enviar</button></form><p data-chat-status></p>','client-chat.js',async(url,opts)=>opts?.method==='POST'?new Promise(r=>postResolve=r):({ok:true,json:async()=>({messages})}));
await settle();const box=w.document.querySelector('[data-chat-url]'),input=w.document.querySelector('textarea'),form=w.document.querySelector('form');
Object.defineProperties(box,{scrollHeight:{get:()=>1000},clientHeight:{get:()=>200}});box.scrollTop=100;input.value='Rascunho';messages=[{id:1,administrator:1,created_at:'agora',body:'<img src=x onerror=alert(1)>'}];await intervals[0]();assert.equal(input.value,'Rascunho');assert.equal(box.scrollTop,100);assert.equal(box.querySelectorAll('article').length,1);assert.equal(box.querySelectorAll('img').length,0);await intervals[0]();assert.equal(box.querySelectorAll('article').length,1);
box.scrollTop=790;messages.push({id:2,administrator:0,created_at:'agora',body:'Nova'});await intervals[0]();assert.equal(box.scrollTop,1000);
form.dispatchEvent(new w.Event('submit',{cancelable:true}));await settle();input.value='Novo texto durante envio';postResolve({ok:true,json:async()=>({ok:true})});await settle();assert.equal(input.value,'Novo texto durante envio');
form.dispatchEvent(new w.Event('submit',{cancelable:true}));await settle();postResolve({ok:false,json:async()=>({error:'Falha simulada'})});await settle();assert.equal(input.value,'Novo texto durante envio');assert.match(w.document.querySelector('[data-chat-status]').textContent,/Falha/);w.close();
let payload;let data={latest:3,unread:1,items:[{id:3,url:'/pedido/1',title:'Mensagem',body:'<script>bad</script>',created_at:'agora',read_at:null}]};const n=setup('<div data-notifications-url="/notificacoes" data-read-url="/lidas" data-csrf="synthetic"><button class="notification-toggle"></button><section class="notification-panel" hidden><button data-read-all>Marcar</button><span data-notification-status></span><ul data-notification-items></ul></section><span data-notification-count></span></div>','notifications.js',async(url,opts)=>{if(opts?.method==='POST'){payload=JSON.parse(opts.body);data={...data,unread:0,items:data.items.map(x=>({...x,read_at:'agora'}))};}return {ok:true,json:async()=>data};});await settle();const doc=n.w.document;assert.equal(doc.querySelector('[data-notification-count]').textContent,'1');assert.equal(doc.querySelectorAll('script').length,0);doc.querySelector('.notification-toggle').click();await settle();assert.equal(doc.querySelector('.notification-panel').hidden,false);doc.querySelector('[data-read-all]').click();await settle();assert.deepEqual(payload,{all:true,through:3});assert.equal(doc.querySelector('[data-notification-count]').hidden,true);doc.dispatchEvent(new n.w.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(doc.querySelector('.notification-panel').hidden,true);n.w.close();console.log('OK: chat (rascunho, rolagem, duplicação, envio/erro, texto seguro) e notificações (contador, leitura, painel, texto seguro).');
})().catch(e=>{console.error(e);process.exit(1)});
