from urllib.parse import quote

business = {
    "name": "FK KÁKA DETAIL",
    "email": "kássyo.albuquerque2527@gmail.com",
    "phone": "(85) 98838-8384",
    "address_line": "Rua Marechal Napion, 775 A",
    "district_city": "Barra do Ceará, Fortaleza — CE",
    "postal_code": "60332-690",
    "weekday_hours": "16h40 às 22h30",
    "weekend_hours": "7h30 às 21h",
}

services = [
    {"slug":"lavagem-detalhada","number":"01","name":"Lavagem detalhada","eyebrow":"Limpeza técnica","summary":"Limpeza criteriosa da pintura, rodas, caixas e pontos que a lavagem comum não alcança.","description":"Uma limpeza conduzida por etapas, com atenção aos materiais e à condição real do veículo. O procedimento é definido após uma avaliação inicial.","objective":"Remover a sujeira acumulada com método e preparar as superfícies para um acabamento uniforme.","steps":["Avaliação visual","Pré-lavagem e descontaminação compatível","Limpeza técnica por áreas","Secagem e inspeção final"],"benefits":["Mais atenção a vincos e emblemas","Acabamento uniforme","Base adequada para proteção"],"aftercare":["Evite produtos domésticos na pintura","Use acessórios limpos e próprios para automóveis","Peça orientação antes de aplicar qualquer proteção"],"faq":[{"question":"É igual a uma lavagem comum?","answer":"Não. A lavagem detalhada segue etapas e considera áreas e materiais que normalmente recebem pouca atenção."}]},
    {"slug":"polimento-tecnico","number":"02","name":"Polimento técnico","eyebrow":"Correção de pintura","summary":"Avaliação e correção compatível com verniz, marcas e estado atual da pintura.","description":"O polimento técnico busca recuperar leitura, profundidade e uniformidade da pintura. A estratégia depende da inspeção do verniz.","objective":"Reduzir defeitos compatíveis com uma correção segura e valorizar o acabamento da pintura.","steps":["Lavagem e descontaminação","Inspeção da pintura","Teste de combinação","Correção por etapas","Refino e inspeção"],"benefits":["Melhor leitura do reflexo","Redução de marcas compatíveis","Preparação para proteção"],"aftercare":["Aguarde a orientação antes da primeira lavagem","Evite panos secos na pintura","Adote uma rotina de lavagem adequada"],"faq":[{"question":"Todo risco desaparece?","answer":"Não. A possibilidade de correção depende da profundidade do defeito e da condição segura do verniz."}]},
    {"slug":"protecao-de-pintura","number":"03","name":"Proteção de pintura","eyebrow":"Conservação","summary":"Camada de proteção escolhida conforme uso, expectativa e condição da superfície.","description":"A proteção correta parte de uma superfície limpa e preparada. A indicação considera rotina de uso, manutenção e resultado desejado.","objective":"Facilitar a manutenção e ajudar a conservar o acabamento exposto ao uso cotidiano.","steps":["Avaliação da superfície","Limpeza e preparação","Aplicação controlada","Cura conforme o produto","Orientação de manutenção"],"benefits":["Manutenção mais previsível","Acabamento valorizado","Proteção compatível com a rotina"],"aftercare":["Respeite o período de cura informado","Use produtos compatíveis","Mantenha a rotina recomendada"],"faq":[{"question":"A proteção elimina a necessidade de lavar?","answer":"Não. Ela facilita a manutenção, mas o veículo continua precisando de uma lavagem correta."}]},
    {"slug":"higienizacao-interna","number":"04","name":"Higienização interna","eyebrow":"Interior","summary":"Cuidado com bancos, carpetes e superfícies para recuperar conforto e aparência.","description":"O interior é avaliado por material e nível de sujidade. Cada área recebe um processo compatível, sem soluções agressivas aplicadas indistintamente.","objective":"Remover a sujidade tratável e devolver uniformidade às superfícies internas.","steps":["Inspeção dos materiais","Aspiração técnica","Limpeza por superfície","Extração quando indicada","Secagem e revisão"],"benefits":["Interior visualmente uniforme","Cuidado específico por material","Mais conforto no uso diário"],"aftercare":["Mantenha o interior ventilado quando orientado","Evite produtos multiuso","Remova resíduos novos o quanto antes"],"faq":[{"question":"O veículo fica pronto no mesmo dia?","answer":"O prazo depende do nível de intervenção e da secagem. A previsão é confirmada após avaliação."}]},
    {"slug":"vitrificacao","number":"05","name":"Vitrificação","eyebrow":"Proteção avançada","summary":"Revestimento aplicado sobre uma preparação cuidadosa, com manutenção orientada.","description":"A vitrificação exige preparação compatível e aplicação controlada. A recomendação é feita somente depois de entender o estado da pintura e a rotina do veículo.","objective":"Criar uma camada de proteção e favorecer a conservação do acabamento ao longo da rotina indicada.","steps":["Diagnóstico da pintura","Correção quando necessária","Preparação química","Aplicação do coating","Cura e entrega técnica"],"benefits":["Comportamento hidrofóbico","Manutenção facilitada","Acabamento protegido"],"aftercare":["Respeite integralmente o período de cura","Não use produtos abrasivos","Faça manutenções conforme a orientação recebida"],"faq":[{"question":"Vitrificação impede riscos?","answer":"Não. Ela não torna a pintura imune a riscos ou impactos; seu papel é ajudar na proteção e manutenção do acabamento."}]},
    {"slug":"revitalizacao-de-plasticos","number":"06","name":"Revitalização de plásticos","eyebrow":"Recuperação visual","summary":"Tratamento de peças internas e externas afetadas por tempo, sol e uso.","description":"O tratamento busca recuperar uniformidade visual respeitando o tipo e a condição de cada plástico.","objective":"Reduzir o aspecto ressecado e recuperar a leitura visual possível da peça.","steps":["Identificação do material","Limpeza da superfície","Aplicação do tratamento","Acabamento e inspeção"],"benefits":["Aparência mais uniforme","Acabamento compatível","Proteção de manutenção"],"aftercare":["Evite desengraxantes agressivos","Use produtos indicados","Reavalie a manutenção periodicamente"],"faq":[{"question":"Toda peça volta a parecer nova?","answer":"Não. O resultado depende do grau de desgaste e da integridade do material."}]},
    {"slug":"detalhamento-de-rodas","number":"07","name":"Detalhamento de rodas","eyebrow":"Precisão","summary":"Limpeza técnica de rodas e pneus com atenção às áreas de acesso difícil.","description":"Rodas, pneus e caixas recebem uma abordagem orientada pelo material e pelo tipo de contaminação encontrado.","objective":"Recuperar a limpeza e o contraste visual do conjunto sem agredir seus acabamentos.","steps":["Inspeção do conjunto","Pré-limpeza","Limpeza técnica","Enxágue e secagem","Acabamento"],"benefits":["Limpeza mais completa","Acabamento uniforme","Melhor leitura do conjunto"],"aftercare":["Evite produtos ácidos sem orientação","Não aplique produto em roda quente","Mantenha intervalos regulares de limpeza"],"faq":[{"question":"Remove toda marca da roda?","answer":"A limpeza trata contaminação. Danos, riscos ou oxidação exigem avaliação específica."}]},
]

whatsapp_number = "5585988388384"
def whatsapp_url(message="Olá, vim pelo site da FK Káka Detail e gostaria de solicitar informações sobre um serviço."):
    return f"https://wa.me/{whatsapp_number}?text={quote(message)}"
